source 'https://github.com/CocoaPods/Specs.git'

target 'SYBlinkAnimationKit_Example' do
    use_frameworks!
    
    pod "SYBlinkAnimationKit", :path => "../"
    
    target 'SYBlinkAnimationKit_Tests' do
        inherit! :search_paths
        pod "SYBlinkAnimationKit", :path => "../"
        pod 'FBSnapshotTestCase'
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "3.0"
        end
    end
end
