source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SYBlinkAnimationKit_Example', :exclusive => true do
  pod "SYBlinkAnimationKit", :path => "../"
end

target 'SYBlinkAnimationKit_Tests', :exclusive => true do
  pod "SYBlinkAnimationKit", :path => "../"

  pod 'FBSnapshotTestCase'
end
